"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 12:50:52.403582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('hours_per_day', sa.Float(), nullable=False),
    sa.Column('days_per_week', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('calculations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('ownership_years', sa.Float(), nullable=True),
    sa.Column('resale_value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('hours_per_day', sa.Float(), nullable=False),
    sa.Column('days_per_week', sa.Float(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculations_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_calculations_user_id'), ['user_id'], unique=False)

    op.create_table('costs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('calculation_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_costs_calculation_id'), ['calculation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_costs_calculation_id'))

    op.drop_table('costs')
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculations_user_id'))
        batch_op.drop_index(batch_op.f('ix_calculations_public_id'))

    op.drop_table('calculations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
