"""budget plan and calculation category

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 14:53:16.999749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pct_needs', sa.Float(), nullable=False),
    sa.Column('pct_future', sa.Float(), nullable=False),
    sa.Column('pct_goals', sa.Float(), nullable=False),
    sa.Column('pct_fun', sa.Float(), nullable=False),
    sa.Column('spent_needs', sa.Float(), nullable=False),
    sa.Column('spent_future', sa.Float(), nullable=False),
    sa.Column('spent_goals', sa.Float(), nullable=False),
    sa.Column('spent_fun', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('already_saved', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('monthly_contribution', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.drop_column('monthly_contribution')
        batch_op.drop_column('already_saved')
        batch_op.drop_column('category')

    op.drop_table('budgets')
    # ### end Alembic commands ###
