"""budget loans

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 08:22:07.440673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_loans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('installment_amount', sa.Float(), nullable=False),
    sa.Column('installments_left', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_loans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_loans_user_id'))

    op.drop_table('budget_loans')
    # ### end Alembic commands ###
