"""money columns as numeric

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-06 14:45:55.794518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_loans', schema=None) as batch_op:
        batch_op.alter_column('installment_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('loan_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('spent_needs',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('spent_future',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('spent_goals',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('spent_fun',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('resale_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('hourly_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=4, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('net_income',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('already_saved',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('monthly_contribution',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)

    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.alter_column('target_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('saved_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)
        batch_op.alter_column('monthly_contribution',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_income',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('hourly_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=4, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('work_costs_monthly',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2, asdecimal=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('work_costs_monthly',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('hourly_rate',
               existing_type=sa.Numeric(precision=14, scale=4, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monthly_income',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.alter_column('monthly_contribution',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('saved_amount',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('target_amount',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.alter_column('monthly_contribution',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('already_saved',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('net_income',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('hourly_rate',
               existing_type=sa.Numeric(precision=14, scale=4, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('resale_value',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('spent_fun',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('spent_goals',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('spent_future',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('spent_needs',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('budget_loans', schema=None) as batch_op:
        batch_op.alter_column('loan_amount',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('installment_amount',
               existing_type=sa.Numeric(precision=14, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
